### ISSUE TITLE
Change ING icon?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pay-logos#13]
https://github.com/pronamic/wp-pay-logos/blob/7d9d9ba6b4e1f8c02b08646d1bc29efcc450f112/src/providers/ing/provider-ing-icon-512x512.svg

![](https://raw.githubusercontent.com/pronamic/wp-pay-logos/main/src/providers/ing/provider-ing-icon-512x512.svg)

> De leeuw mag volgens de ING Logo Guidelines niet op deze worden gebruikt:
> 
> <img width="413" alt="Scherm­afbeelding 2024-05-28 om 11 42 52" src="https://github.com/pronamic/pronamicpay.com/assets/610613/a859c7a3-a359-4495-8fac-83b0e053eebf">
> 
> Bron: https://assets.ing.com/m/a8316ae4a3e95434/LogoGuidelines.pdf
> 
> In de guidelines staat ook wel hoe het logo bij voorkeur moet worden gebruikt.
> 
> <img width="1625" alt="Scherm­afbeelding 2024-05-28 om 11 58 39" src="https://github.com/pronamic/pronamicpay.com/assets/610613/18389978-b1e3-4635-be3c-949713c38a8d">

_Originally posted by @LeoOosterloo in https://github.com/pronamic/pronamicpay.com/issues/89#issuecomment-2134819663_

**Comment by LeoOosterloo** [comment]
Ik krijg niet eens de kans om zelf een issue aan te maken ;-). Was daar namelijk al mee bezig en heb de SVG's al gemaakt:

![provider-ing-icon-512x512](https://github.com/pronamic/wp-pay-logos/assets/610613/d1f4a181-a7f9-41df-8141-16902f2beeb1)
![provider-ing-icon-black-512x512](https://github.com/pronamic/wp-pay-logos/assets/610613/887edfbe-8e00-4190-a2ca-c2ae7e5c7261)
![provider-ing-icon-white-512x512](https://github.com/pronamic/wp-pay-logos/assets/610613/be7ec8af-ab78-4e6a-9c1c-57894b59ba0f)

**Comment by LeoOosterloo** [comment]
I also updated the full logo with the correct alignment of the lion and the text. Also updated the HEX color of the logo's according to the LogoGuidelines.

[provider-ing-logos.zip](https://github.com/pronamic/wp-pay-logos/files/15467900/provider-ing-logos.zip)

@remcotolsma can you update the logo's in the repository?

**Comment by remcotolsma** [comment]
> I already made the SVG's for correct use of the icon logo:

What source did you exactly use for these SVG's? The complete lion is in these files? Have you determined the position manually? I also notice a white shadow in these files?

<img width="902" alt="Scherm­afbeelding 2024-05-28 om 14 02 46" src="https://github.com/pronamic/wp-pay-logos/assets/869674/6971dffa-70ac-4603-90db-85bb0d84ffb8">

> Did you recreate the close-up of the lion, or is it from an official ING source file?
> 
> I also updated the full logo with the correct alignment of the lion and the text. Also updated the HEX color of the logo's according to the LogoGuidelines.
> 
> [provider-ing-logos.zip](https://github.com/pronamic/wp-pay-logos/files/15467900/provider-ing-logos.zip)
> 
> @remcotolsma can you update the logo's in the repository?

This issues is about the icon, can you open up a new issue for the logo?
https://github.com/pronamic/wp-pay-logos/blob/7d9d9ba6b4e1f8c02b08646d1bc29efcc450f112/src/providers/ing/provider-ing-640x360.svg

**Comment by LeoOosterloo** [comment]
> Did you recreate the close-up of the lion, or is it from an official ING source file?

I did use an official logo earlier already. I now updated the logo from the Logo Guidelines file. There is still a white background in the head, but now without the 'borders'.

![provider-ing-icon-512x512](https://github.com/pronamic/wp-pay-logos/assets/610613/601e260b-7ccc-4cd4-ae56-35dcc0097e11)
![provider-ing-icon-black-512x512](https://github.com/pronamic/wp-pay-logos/assets/610613/6a5747bd-7e6b-4470-867c-6e33d322600f)

**Comment by remcotolsma** [comment]
I have created the icon files myself from the `LogoGuidelines.pdf` file to be sure of the origin.

- https://github.com/pronamic/wp-pay-logos/blob/3f4aa4b37fdecd2d772efccb1590eb9b417c9df3/dist/providers/ing/provider-ing-icon-512x512.svg
- https://github.com/pronamic/wp-pay-logos/blob/3f4aa4b37fdecd2d772efccb1590eb9b417c9df3/dist/providers/ing/provider-ing-icon-black-512x512.svg
- https://github.com/pronamic/wp-pay-logos/blob/3f4aa4b37fdecd2d772efccb1590eb9b417c9df3/dist/providers/ing/provider-ing-icon-white-512x512.svg

**Comment by remcotolsma** [comment]
Confused 😕 about why I recreated them myself @LeoOosterloo? I had already recreated them myself, because your previous input contained possible inaccuracies. I was waiting for the answers to my questions, I wasn't necessarily asking you to create new ones yourself.
