### ISSUE TITLE
Change SEPA logo?

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pay-logos#14]
@remcotolsma mentioned:

> En voor SEPA hanteren we ook een ander logo: https://github.com/pronamic/wp-pay-logos/blob/7d9d9ba6b4e1f8c02b08646d1bc29efcc450f112/src/other/sepa/sepa-640x360.svg.

So I checked this and the colors are not correct. I updated the logo's the following ZIP.
[sepa-logos.zip](https://github.com/pronamic/wp-pay-logos/files/15469254/sepa-logos.zip)

Can you update this in the repository @remcotolsma?

**Comment by remcotolsma** [comment]
> So I checked this and the colors are not correct.

Source?

---

The current logo comes from the following:

> To our knowledge, no official branding is available for SEPA. We did find a vector logo in the `EPC346-08 v6.0 Shortcut to the SEPA Data Format.pdf` file:
> 
> https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC346-08%20v6.0%20Shortcut%20to%20the%20SEPA%20Data%20Format.pdf

_Source: https://github.com/pronamic/wp-pay-logos/tree/7d9d9ba6b4e1f8c02b08646d1bc29efcc450f112/src/other/sepa_

**Comment by LeoOosterloo** [comment]
Source: https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2022-03/EPC034-08%20v.1.0%20VIG%20SEPA%20logo%20new%20template.pdf

And: https://www.europeanpaymentscouncil.eu/document-library/other/sepa-logo-vector-format

All colors from these sources are CMYK based. You can see a clear difference in the communicated logo from the "SEPA Logo Visual Identity Guidelines" and the logo we use.

**Comment by remcotolsma** [comment]
I have a PR open:

- https://github.com/pronamic/wp-pay-logos/pull/16

How did you get the RGB-codes @LeoOosterloo?

I have other RGB-codes:

- Blue → Leo: `#0054a6` Remco: `#10298F`
- Yellow → Leo: `#ffc20d` Remco: `#FFBE00`

**Comment by LeoOosterloo** [comment]
> How did you get the RGB-codes @LeoOosterloo?

Exporting the EPS to SVG and opening the SVG in Figma.

If you think your color codes are correct, feel free to adjust them.

**Comment by remcotolsma** [comment]
How did you export the EPS to SVG?

**Comment by LeoOosterloo** [comment]
> How did you export the EPS to SVG?

https://affinity.serif.com/en-us/designer/

**Comment by kjtolsma** [comment]
I opened the .EPS in Sketch and it shows these color codes. More to indicate that you don't just get the RGB colors from this .EPS.
