### ISSUE TITLE
Change ING logo

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pay-logos#15]
As requested in https://github.com/pronamic/wp-pay-logos/issues/13#issuecomment-2135055242:

> This issues is about the icon, can you open up a new issue for the logo?
https://github.com/pronamic/wp-pay-logos/blob/7d9d9ba6b4e1f8c02b08646d1bc29efcc450f112/src/providers/ing/provider-ing-640x360.svg

The updated logo's:
![provider-ing-640x360-white](https://github.com/pronamic/wp-pay-logos/assets/610613/66663805-5723-4dfd-b9de-c91d0148a061)
![provider-ing-640x360](https://github.com/pronamic/wp-pay-logos/assets/610613/c995a89b-df45-43cc-9172-5c707eb92280)

**Comment by remcotolsma** [comment]
Can you provide some context? Is there a problem in the current files?

**Comment by LeoOosterloo** [comment]
> Besides that the #hex codes where not correct according to the logo guidelines.

The new SVG's use the correct Hex codes `#FF6200` & `#000066`.

<img width="814" alt="Scherm­afbeelding 2024-05-28 om 16 58 50" src="https://github.com/pronamic/wp-pay-logos/assets/610613/385fc394-f619-4b21-988f-bfe6d9e9d10c">

**Comment by remcotolsma** [comment]
I have created the logo files myself from the `LogoGuidelines.pdf` file to be sure of the origin:

- https://github.com/pronamic/wp-pay-logos/blob/3f4aa4b37fdecd2d772efccb1590eb9b417c9df3/dist/providers/ing/provider-ing-640x360.svg
- https://github.com/pronamic/wp-pay-logos/blob/3f4aa4b37fdecd2d772efccb1590eb9b417c9df3/dist/providers/ing/provider-ing-white-640x360.svg

Also added some documentation in https://github.com/pronamic/wp-pay-logos/blob/0a33d1e0c99bd39385a1a211348df045704185c6/src/providers/ing/README.md.
