### ISSUE TITLE
Update Bancontact logo

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pay-logos#8]
For the use of the Bancontact logo there are some banding guidelines provided:
https://www.bancontact.com/en/promotion-material/guidelines-logo

I made some changes in the use of the logo to better follow the guidelines.
[bancontact.zip](https://github.com/pronamic/wp-pay-logos/files/12395946/bancontact.zip)

**Comment by remcotolsma** [comment]
What did you exactly change @LeoOosterloo compared to the current one?
https://github.com/pronamic/wp-pay-logos/tree/main/src/methods/bancontact

By the way, you don't have to provide the PNG and @2x, @3x, @4x versions, we have written scripts that automatically generate these versions.

**Comment by LeoOosterloo** [comment]
The icon should always have a white background around the logo.
For example the way we use it on https://www.pronamicpay.com/nl/koppelingen/bancontact-voor-gravity-forms/ is not allowed according the guidelines.
